name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Setup C++
        uses: aminya/setup-cpp@v1
        with:
          compiler: clang
          cmake: true
          ninja: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Go protobuf plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Generate protobuf
        run: make proto

      - name: Build Go services
        run: make build-go

      - name: Build C++ targets
        run: make build-cpp

      - name: Build web
        working-directory: web
        run: |
          npm ci
          npm run build --if-present

      - name: Build launcher
        working-directory: launcher
        run: |
          npm ci
          npm run build --if-present
